server:
    port: 8080

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: 
        databaseName: boardatjob
        serverName: localhost
        username: boardatjob
        password: 

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: true
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            max_fetch_depth: 2
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    data:
        elasticsearch:
            cluster-name: 
            cluster-nodes: 
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data 
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: boardatjob


